
---기말고사 1번 문제 
SELECT BRAND_CD
,ITEM_CD
,SUM(ORDER_QTY)AS ORDER_QTY
,CASE WHEN (ORDER_QTY/2)=0 THEN '홀' ELSE '짝' 
END AS EVENODD
FROM A_OUT_D 
GROUP by BRAND_CD, ITEM_CD, CASE WHEN (ORDER_QTY/2)=0 THEN '홀' ELSE '짝' END
ORDER BY BRAND_CD, ITEM_CD, CASE WHEN (ORDER_QTY/2)=0 THEN '홀' ELSE '짝' END ,ORDER_QTY DESC;
;

---기말고사 2번 문제 
SELECT BRAND_CD
,COUNT(INVOICE_NO)
,COUNT(MAX(OUTBOUND_DATE)-MIN(OUTBOUND_DATE))AS DAY_CNT
,MIN(OUTBOUND_DATE)AS DATE_MIN
,MAX(OUTBOUND_DATE)AS DATE_MAX
FROM A_OUT_M
GROUP BY BRAND_CD,
ORDER BY BRAND_CD;

--기말고사 3번 문제 
SELECT BRAND_CD,ITEM_CD,SUM(ORDER_QTY)
CASE WHEN ORDER_QTY >=3 THEN ORDER_QTY 
END AS SUM_QTY
    FROM A_OUT_D
    GROUP BY BRAND_CD, ITEM_CD,CASE WHEN ORDER_QTY >=3 THEN ORDER_QTY
    END
    ORDER BY BRAND_CD;
    
--기말고사 4번 문제 
SELECT *
FROM A_OUT_M;

SELECT 
BRAND_CD
,TO_CHAR(OUTBOUND_DATE,'D')AS DAY
,COUNT(INVOICE_NO)AS INVOICE_CNT
FROM A_OUT_M
GROUP BY BRAND_CD
,TO_CHAR(OUTBOUND_DATE,'D')AS DAY
,COUNT(INVOICE_NO)
ORDER BY BRAND_CD;

--기말문제 5
SELECT BRAND_CD,ITEM_CD,SUM(ORDER_QTY)AS SUM_QTY
,CASE WHEN SUM(ORDER_QTY)>=5 THEN '상'
,CASE WHEN SUM(ORDER_QTY)=3 OR SUM(ORDER_QTY)=4 THEN '중'
,CASE WHEN SUM(ORDER_QTY)=1 OR SUM(ORDER_QTY)=2 THEN '하'
END AS GRADE 
FROM A_OUT_D
GROUP BY BRAND_CD
ORDER BY BRAND_CD
,CASE SUM(ORDER_QTY) >=5 THEN '상'
,CASE  SUM(ORDER_QTY)=3 OR SUM(ORDER_QTY)=4 THEN '중'
,CASE SUM(ORDER_QTY)=1 OR SUM(ORDER_QTY)=2 THEN '하'
END;

----- 기말고사문제 6
SELECT BRAND_CD, INVOICE_NO,SUM(ORDER_QTY)AS SUM_QTY
FROM A_OUT_D 
GROUP BY BRAND_CD, INVOICE_NO
ORDER BY BRAND_CD, INVOICE_NO;

--기말고사 문제 7
SELECT ITEM_CD,SUM(ORDER_QTY)
,CASE WHEN ITEM_CD
,
  FROM A_OUT_D

--기말고사 문제 8
--기말고사 문제 9
--기말고사 문제 10



